spring:
  datasource:
    hikari.maximum-pool-size: 4
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
  security:
    user:
      name:
      password:
  cloud:
    gcp:
      credentials:
        location: file:${user.home}/config/omoji-server-account.json
gcp:
  config:
    file: ${user.home}/config/omoji-server-account.json
  project:
    id: omoji-server
  bucket:
    id: omoji-bucket
  dir:
    name: img