spring:
  datasource:
    hikari.maximum-pool-size: 4
    driver-class-name: org.postgresql.Driver
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWD}
  security:
    user:
      name: ${SECURITY_ID}
      password: ${SECURITY_PW}
  cloud:
    gcp:
      credentials:
        location: classpath:omoji-server-account.json
gcp:
  config:
    file: omoji-server-account.json
  project:
    id: omoji-server
  bucket:
    id: omoji-bucket
  dir:
    name: img