#local, dev, prod 공통 설정
application:
  version: 1.0.0
  title: omoji

spring:
  datasource:
    schema: schema-postgres.sql
    data: data-postgres.sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
#      mode: always //한 번 hashtag 생성 후엔 다시 하지마라
      platform: postgres
  jpa:
    open-in-view: false
    database: postgresql
    hibernate:
      default_batch_fetch_size: 100
      dialect: org.hibernate.dialect.PostgreSQLDialect
      datasource:
          initialization: true
    properties:
      hibernate:
        format_sql: true
server:
  forward-headers-strategy: framework
  use-forward-headers: true
--- #local 환경
spring:
  config:
    activate:
      on-profile: local
    import: application-oauth.yml
  jpa.hibernate.ddl-auto: none
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
--- #dev 환경
spring:
  config:
    activate:
      on-profile: dev
    import: application-oauth.yml
logging:
  level:
    root: info

--- #prod 환경
spring:
  config:
    activate:
      on-profile: prod
    jpa.hibernate.ddl-auto: none
    import: application-oauth.yml
server:
  port: 9090
logging:
  level:
    root: info